spring:
  datasource:
    url: jdbc:h2:mem:testdb
    driver-class-name: org.h2.Driver
    username: sa
    password:
    platform: h2
  h2:
    console:
      enabled: true
  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: false
      javax:
        persistence:
          schema-generation:
            database:
              action: create
server:
  port: 8080
logging:
  level:
    root: warn
    com.pablozoani: debug